### ISSUE TITLE
Should we store 'navigation' in mobX store?

### ISSUE THREAD

**Issue by benevbright** [dooboolab/talktalk-rn#1]
I couldn't find an advantage that we store `navigation props` in the mobX store.
Do you have any idea?

**Comment by dooboolab** [comment]
@benevbright Yes. That was in case to handle different navigators globally. However, we can get rid of it.

**Comment by dooboolab** [comment]
@benevbright I've just done it [here](https://github.com/dooboolab/talktalk-rn/commit/3d2e43936b7214a7492ba0c44a7528f242585e2c). Close this for now. Thanks.

**Comment by benevbright** [comment]
I created PR for removing globar navigator. #4 

I think we consider it when we need it. 
Until that, I think a more plain way will be better to understand.
